### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by piqihaha** [GravelFire/MajorBot#12] opened 2024-08-29 06:13 UTC
2024-08-29 14:09:27 | INFO | 5_rodahban | Proxy IP: 103.142.140.246
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F8BEDB7020>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001F8BEDAE990>, 1258481.375)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x000001F8BEDAE6F0>, 1258482.734)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001F8BED6D190>
2024-08-29 14:09:30 | INFO | 5_rodahban | ⭐ Login successful
2024-08-29 14:09:31 | INFO | 5_rodahban | ID: 6658530752 | Points : 53439
2024-08-29 14:09:34 | INFO | 2_Farhan | Proxy IP: 212.107.30.68
2024-08-29 14:09:36 | INFO | 5_rodahban | Squad : HiddenCode | Member : 7185 | Ratings : 7639935
2024-08-29 14:09:37 | INFO | 5_rodahban | Daily Streak : 2
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F8BEDC54C0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001F8BEDAEAB0>, 1258490.484)]']
connector: <aiohttp_proxy.connector.ProxyConnector object at 0x000001F8BEDB6EA0>
2024-08-29 14:09:40 | INFO | 5_rodahban | Success Claim 593 Coins

what happening

**Comment by Nord1cWarr1or** [comment] 2024-08-29 22:03
duplicate of #10

**Closed as completed** 2024-09-06 08:38 UTC
